apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: mern
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mern
      tier: frontend
  template:
    metadata:
      labels:
        app: mern
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: tejasbi/frontend-app:latest-6
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
  selector:
    app: mern
    tier: frontend
