apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: mern
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mern
      tier: backend
  template:
    metadata:
      labels:
        app: mern
        tier: backend
    spec:
      containers:
      - name: backend
        image: tejasbi/backend-app:latest-6
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: mern
    tier: backend
